name: Bug Report
description: Report a bug or issue with foundry-dev-tools
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees:
  - rayners

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @rayners/foundry-dev-tools are you using?
      placeholder: "e.g., 1.0.6"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is experiencing the issue?
      options:
        - Rollup Configuration
        - ESLint Configuration
        - Prettier Configuration
        - TypeScript Configuration
        - Vitest Configuration
        - Build Process
        - GitHub Workflows
        - Package Structure
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Install package with...
        2. Configure...
        3. Run command...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your development environment
      value: |
        - Node.js version: 
        - npm version: 
        - Operating System: 
        - Project type: (Foundry module/other)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add any error logs or console output
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration Files
      description: If relevant, paste your configuration (package.json, rollup config, etc.)
      render: json

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I am using a supported Node.js version (18.x, 20.x, or 22.x)
          required: true