name: Feature Request
description: Suggest a new feature or enhancement for foundry-dev-tools
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees:
  - rayners

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about what you'd like to see added.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature enhance?
      options:
        - Rollup Configuration
        - ESLint Configuration
        - Prettier Configuration
        - TypeScript Configuration
        - Vitest Configuration
        - Build Process
        - GitHub Workflows
        - Package Structure
        - New Component
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Configuration Option
        - New Build Tool Integration
        - Performance Improvement
        - Developer Experience Enhancement
        - Documentation Improvement
        - Testing Enhancement
        - CI/CD Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see added.
      placeholder: One-line description of the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: Explain the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the proposed feature.
      placeholder: Describe the feature in detail...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Show how this feature would be used.
      placeholder: |
        ```javascript
        // Example usage
        ```
      render: javascript

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Needed for current project
        - Critical - Blocking development
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small configuration change
        - Medium - New feature with existing patterns
        - Complex - Major new functionality
        - Unknown - Not sure

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to write documentation for this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: This feature would benefit the broader foundry-dev-tools user community
          required: true
        - label: I have provided clear examples and use cases
          required: true